### ISSUE TITLE
Implementar um sidebar menu na tela de recarga

### ISSUE THREAD

**Issue by mbrutzig** [Projeto-Wallbox/Aplicativo#10]
Para implementar este menu deve-se:
- Inserir os seguintes items:
	Home:
		- Este item aparecerá para todos os perfis de usuários
	Recarga:
		- Este item aparecerá somente para os perfis de dono e técnico
	Veículos
		- Este item aparecerá somente para os perfis de dono e técnico
	Agendamentos 
		- Este item aparecerá somente para os perfis de dono e técnico
	Estatísticas:
		- Este item aparecerá somente para os perfis de dono e técnico
	Usuários:
                 - Este item aparecerá somente para os perfis de dono e técnico
	Configuração WiFi:
		- Este item aparecerá somente para os perfis de dono e técnico
	Configurações Avançadas:
                - Este item aparecerá somente para o perfil de técnico

**Comment by crazynds** [comment]
A home já é a tela de carregamento. 
Eu fiz baseado nas permissões de login. No wallbox de test eu gero uma permissao aleatoria pra cada vez q acontece o login.
