### ISSUE TITLE
Implementar as telas do item do sidebar Veículos

### ISSUE THREAD

**Issue by mbrutzig** [Projeto-Wallbox/Aplicativo#12]
Para implementar esta função:
	- Criar uma tela que liste todos os veículos já cadastrados (tela 8), com a possibilidade de remover com um ícone ao lado do veículo. No canto direito inferior, a tela deve conter um botão para adicionar um novo veículo.
	- Criar uma tela que ao clicar no botão de adicionar o veículo apresente os seguintes campos (tela 12): Nome, Modelo, Ano, Capacidade da bateria (mAh). Um botão “Salvar” deve ser inserido e ao ser pressionado retorna a tela da lista de veículos.

**Comment by crazynds** [comment]
Isso já ta feito.
