### ISSUE TITLE
Montar o Entidade Relacionamento do BD

### ISSUE THREAD

**Issue by mbrutzig** [Projeto-Wallbox/Aplicativo#3]

**Comment by crazynds** [comment]
Segue a entidade que fiz baseado nas informações do UserStories

![image](https://github.com/Projeto-Wallbox/Aplicativo/assets/36674096/12090255-aebb-44c0-84b4-51954e3e946c)

**Comment by crazynds** [comment]
As colunas podem mudar, mas as tabelas são só essas.

A tabela usuário não é o aplicativo que vai gerenciar.
