### ISSUE TITLE
Implementar a função para adicionar/deletar estações de recarga

### ISSUE THREAD

**Issue by mbrutzig** [Projeto-Wallbox/Aplicativo#8]
Para implementar a inserção e remoção de estações de recarga deve-se:
- Criar uma tela que liste todos wallbox disponíveis na rede conectada pelo celular
- Criar uma tela que, após a seleção da rede do wallbox, o usuário deve ser capaz de selecionar o tipo de usuário (técnico, dono, inquilino), inserir o usuário e senha e clicar em “Adicionar” (após o clique em adicionar o aplicativo de retornar para a tela que lista as estações de recarga).

**Comment by crazynds** [comment]
Eu não achei uma maneira fácil de resolver alguns problemas:
 - Exibir wallbox salvo mas que não está conectado na rede atual
 - Ao mudar o ip do wallbox meio que ele não 'identifica' ele.
 - Ao remover um usuario ou editar a senha, o wallbox salvo no dispositivo não consegue fazer o sync e logo fica inutilizave.
 
Eu resolvi modificar essa tela para algo mais simples, pois não faz sentido ter q cadastrar o walbox. 
Removi o botão de +, e agora eu listo todos os wallbox da rede atual (Como os wallbox vão vir com nomes facilita a identificação por parte do usuário). Se o usuário já se conectou uma vez no wallbox e tem a senha e usuario salvo, o wallbox aparece com uma cor diferente.
Estou agora identificando os wallbox pelo mac.

O principal motivo de fazer isso é que é bem desnecessário criar um CRUD de wallbox, se ele só vai poder se conectar aos wallbox locais. Mesmo que eu liste todos os wallbox, se ele não tiver na rede não tem como conectar, então não tem proposito listar todos, e se eu for listar só os que ele encontrar na rede, faz muito mais sentido listar todos que ele vai encontrar na rede (não deve passar de 4 ou 5), e os que ele já conectou vão ter cor diferente.
