### ISSUE TITLE
Implementar a função de ativar/desativar uma recarga

### ISSUE THREAD

**Issue by mbrutzig** [Projeto-Wallbox/Aplicativo#9]
Para implementar esta função deve-se:
- Criar uma tela com um toggle button com a possibilidade de ativar/desativar uma recarga.
- Nesta tela o usuário poderá escolher o veículo a ser recarregado. Também poderá inserir a porcentagem atual de carga da bateria, esta informação possibilitará estimar o tempo restante de recarga.
- Nesta tela o usuário poderá visualizar, sob demanda, as seguintes informações da recarga: Energia (KWh), Potência (W), Tempo estimado completar a carga da bateria (h,min).

**Comment by crazynds** [comment]
A tela feita e botão colocado.
